spring:
  application:
    name: api-backoffice
  profiles:
    active: local
    include: datasource, openapi, logging, core

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 10002

---
spring:
  config:
    activate:
      on-profile: dev
    import: aws-secretsmanager:/secret/pay200
