spring:
    application:
        name: api
    profiles:
        active: local
        include: datasource

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html


