spring:
  application:
    name: api
  profiles:
    active: local
    include: infra, openapi
  jackson:
    deserialization:
      use-big-decimal-for-floats: true

server:
  port: 8080
card:
  url:
    base-url: http://localhost:8082
    approve-end-point: /mock/card/approve
    validate-end-point: /mock/card/validate

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 10001

card:
  url:
    base-url: http://localhost:8082
    approve-end-point: /mock/card/approve
    validate-end-point: /mock/card/validate

---
spring:
  config:
    activate:
      on-profile: dev
    import: aws-secretsmanager:/secret/pay200

card:
  url:
    base-url: http://localhost:8082
    approve-end-point: /mock/card/approve
    validate-end-point: /mock/card/validate
