spring:
  application:
    name: api
  profiles:
    active: local
    include: infra, openapi

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 10001

---
spring:
  config:
    activate:
      on-profile: dev
    import: aws-secretsmanager:/secret/pay200
