spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:${test-container.postgres.port}/backoffice
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 30000 # 5분
      connection-timeout: 20000 # 30초
      max-lifetime: 1800000 # 30분

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:sql/data.sql
      mode: always

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:backoffice
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_URL}/backoffice
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PW}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 30000 # 5분
      connection-timeout: 20000 # 30초
      max-lifetime: 1800000 # 30분
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true
